import React from 'react'
import './Styles/Experience.css'
import twilightbackground from '../Images/twilightbackground.jpg'
import JobComp from '../Components/ExperienceComp/JobComp'
import LineAndBorder from '../Components/AboutComp/LineAndBorder'
import { motion, useScroll , useAnimation} from "framer-motion"

import GoogleLogo from '../Images/jobsLogo/googlelogo.png'
import CodeNinjasLogo from '../Images/jobsLogo/codeninjaslogo.png'
import CskLogo from '../Images/jobsLogo/csklogo.png'
import CycLogo from '../Images/jobsLogo/cyclogo.webp'
import AcornLogo from '../Images/jobsLogo/acornlogo.jpeg'
import WiCSLogo from '../Images/jobsLogo/wics.png'


export const Experience = () => {
  const backgroundStyle = {
    background: `linear-gradient(to bottom, rgba(0, 0, 0, 0) 0%, #01010c 120%), url(${twilightbackground})`,
    backgroundSize: "cover",      // Ensures the image covers the entire div
    backgroundPosition: "center", // Centers the background image
    backgroundRepeat: "no-repeat", // Prevents the image from repeating
    justifyContent: 'center',
    alignItems: 'center'
  };

  return (
    <div id="experience" style={backgroundStyle}>
      <br></br>
      <h1>My Experience Journey</h1>
      <br></br>
        <motion.div className='indJobComp'
        whileInView={{ x: 0, // Start at the final position (0)
        opacity: 1,  transition: { duration: 3 }}} initial={{x: '-10vw', opacity: 0}}
        >
          <LineAndBorder
          text = "h1"
          textColor = 'SlateBlue'
          borderColor = '#5b358c'
          />
          <JobComp
          logo = {GoogleLogo}
          jobTitle = "Google STEP Intern"
          jobName = "Google LLC | Google Fi | Fraud & Abuse"
          date = "May 2024 -> Aug 2024"
          point1 = "Architected an automated daily running C++ pipeline using Google's internal tools to extract data about Google Fi users, simplifying  Google Fi latency by 90 percent."
          point2 = "Created a workflow that queried data in SQL to a dashboard to read and display historical and current statistical information generated by the pipelines output."
          point3 = "Executed writing pipeline and dashboard design doc's with detailed description of project workflow, visuals, background information, project impact and steps, alternative solutions and scalable features."
          ></JobComp>
        </motion.div>

        <motion.div className='indJobComp'
        whileInView={{ x: 0, // Start at the final position (0)
        opacity: 1,  transition: { duration: 3 }}} initial={{x: '10vw', opacity: 0}}>
        
          <JobComp
          logo = {WiCSLogo}
          jobTitle = "WiCS Dev Project"
          jobName = "Women in Computer Science"
          date = "Jan 2025 -> May 2025"
          point1 = "Work with the UIC Women in Computer Science club to create the club website using Astro and tailwind."
          point2 = "Created fully responsive socials and timeline component along with styling the events component."
          point3 = "Collaborated with a large team using github to ensure a successfull integration of components."
          ></JobComp>
          <LineAndBorder
            text = "h1"
            textColor = 'Orange'
            borderColor = '#a36b33'
          />
        </motion.div>
        <br></br>
        
        <br></br>
        <motion.div className='indJobComp'
        whileInView={{ x: 0, // Start at the final position (0)
        opacity: 1,  transition: { duration: 3 }}} initial={{x: '-10vw', opacity: 0}}
        >
          <LineAndBorder
            text = "h1"
            textColor = '#8c3555'
            borderColor = '#52172c'
          />
        <JobComp
          logo = {CodeNinjasLogo}
          jobTitle = "Code Instructor"
          jobName = "Code Ninjas"
          date = "May 2024 -> Aug 2024"
          point1 = "Architected an automated daily running C++ pipeline using Google's internal tools to extract data about Google Fi users, simplifying  Google Fi latency by 90 percent."
          point2 = "Created a workflow that queried data in SQL to a dashboard to read and display historical and current statistical information generated by the pipelines output."
          point3 = "Executed writing pipeline and dashboard design doc's with detailed description of project workflow, visuals, background information, project impact and steps, alternative solutions and scalable features."
          ></JobComp>
          
        </motion.div>
        <br></br>
        <br></br>
        <motion.div className='indJobComp'
        whileInView={{ x: 0, // Start at the final position (0)
        opacity: 1,  transition: { duration: 3 }}} initial={{x: '10vw', opacity: 0}}>
        
        <JobComp
          logo = {CycLogo}
          jobTitle = "Youth Leader/Database Developer"
          jobName = "Code Your Chances"
          date = "May 2024 -> Aug 2024"
          point1 = "Architected an automated daily running C++ pipeline using Google's internal tools to extract data about Google Fi users, simplifying  Google Fi latency by 90 percent."
          point2 = "Created a workflow that queried data in SQL to a dashboard to read and display historical and current statistical information generated by the pipelines output."
          point3 = "Executed writing pipeline and dashboard design doc's with detailed description of project workflow, visuals, background information, project impact and steps, alternative solutions and scalable features."
          ></JobComp>
          <LineAndBorder
            text = "h1"
            textColor = '#52bab3'
            borderColor = '#358c86'
          />
        </motion.div>
        <br></br>
        <motion.div className='indJobComp'
        whileInView={{ x: 0, // Start at the final position (0)
        opacity: 1,  transition: { duration: 3 }}} initial={{x: '-10vw', opacity: 0}}>
          <LineAndBorder
            text = "h1"
            textColor = '#4c8fc2'
            borderColor = '#35668c'
          />
          <JobComp
          logo = {AcornLogo}
          jobTitle = "Front-end Developer Assistant Intern"
          jobName = "Acorn Genetics"
          date = "May 2024 -> Aug 2024"
          point1 = "Architected an automated daily running C++ pipeline using Google's internal tools to extract data about Google Fi users, simplifying  Google Fi latency by 90 percent."
          point2 = "Created a workflow that queried data in SQL to a dashboard to read and display historical and current statistical information generated by the pipelines output."
          point3 = "Executed writing pipeline and dashboard design doc's with detailed description of project workflow, visuals, background information, project impact and steps, alternative solutions and scalable features."
          ></JobComp>
          
        </motion.div>
        <br></br>
        <motion.div className='indJobComp'
        whileInView={{ x: 0, // Start at the final position (0)
        opacity: 1,  transition: { duration: 3 }}} initial={{x: '10vw', opacity: 0}}>
        
          <JobComp
          logo = {CskLogo}
          jobTitle = "Coding Club President"
          jobName = "CompSciKids"
          date = "May 2024 -> Aug 2024"
          point1 = "Architected an automated daily running C++ pipeline using Google's internal tools to extract data about Google Fi users, simplifying  Google Fi latency by 90 percent."
          point2 = "Created a workflow that queried data in SQL to a dashboard to read and display historical and current statistical information generated by the pipelines output."
          point3 = "Executed writing pipeline and dashboard design doc's with detailed description of project workflow, visuals, background information, project impact and steps, alternative solutions and scalable features."
          ></JobComp>
          <LineAndBorder
            text = "h1"
            textColor = 'Orange'
            borderColor = '#a36b33'
          />
        </motion.div>
        <br></br>
    </div>
  )
}
